// This file contains the configuration for the cadastropessoa test suite.
export const cadastroMembroFamiliar = { 
    baseurl: "https://dev.joaopessoa.pb.gov.br/ords/r/master/social/social0013?session=31207475505279",  

    dadosMembro: {
        selectors: {
            nomecompleto: "P13_NM_PESSOA",
            labeltitular: "P13_FL_TITULAR_LABEL",
            possuinomesocial: "P13_FL_NM_SOCIAL_LABEL",
            generolovbtn: "P13_ID_GENERO",
            orientacaosexual: "P13_NM_ORIENTACAO_SEXUAL",
            datanascimento: "P13_DT_NASCIMENTO_input",
            cpf: "P13_NU_CPF",
            email: "P13_DS_EMAIL",
            telefone: "P13_DS_TELEFONE",
            nis: "P13_NU_NIS",
            rg: "P13_NU_RG",
            nomepai: "P13_NM_PAI",
            nomemae: "P13_NM_MAE",
            estadocivil: "P13_ID_ESTADO_CIVIL", 
            escolaridade: "P13_ID_ESCOLARIDADE",
            nacionalidade: "P13_ID_NACIONALIDADE",
            naturalidade: "P13_ID_NATURALIDADE",
            etnia: "P13_ID_ETNIA",
            demandante: "P13_NM_DEMANDANTE",
            numerocartaosus: "P13_NU_CARTAO_SUS", 
            deficiencia: "P13_FL_DEFICIENCIA_LABEL",
            comorbidade: "P13_FL_COMORBIDADE_LABEL", 
            medicacao: "P13_FL_MEDICACAO_LABEL", 
            orgaoorigem: "P13_ID_ORGAO_ORIGEM",
            banco: "P13_ID_BANCO",
            agencia: "P13_NU_AGENCIA",
            conta: "P13_NU_CONTA",
            operacao: "P13_NU_OPERACAO",
            observacao: "P13_DS_OBSERVACAO_1", 

            // seleção do titular
            //cpftitularresponsavel: "P13_LISTA",

            // endereço (agora em lowercase)
            cep: "P13_NU_CEP",
            endereco: "P13_NM_ENDERECO",
            numero: "P13_NU_ENDERECO",
            bairro: "P13_NM_BAIRRO",
            cidade: "P13_NM_CIDADE",
            uf: "P13_CD_UF",
            complemento: "P13_DS_COMPLEMENTO",
            tipo_localidade: "P13_FL_TIPO_LOCALIDADE",
            tipo_construcao: "P13_FL_TIPO_CONSTRUCAO",
            coabitacao_familiar: "P13_FL_COABITACAO",
            iluminacao: "P13_FL_ILUMINACAO",
            domicilio_coberto_por: "P13_FL_DOMICILIO_COBERTO_POR_LABEL",
            abastecimento_de_agua: "P13_FL_ABASTECIMENTO_AGUA",
            esgoto_sanitario: "P13_FL_ESGOTO",
            destino_do_lixo: "P13_FL_DESTINO_LIXO",
            condicao_da_moradia: "P13_ID_CONDICAO_MORADIA",
            descricao_da_moradia: "P13_DS_IMOVEL",
            tipo_domicilio: "P13_TIPO_DE_DOMICILIO",

            // situação da pessoa 
            situacaonomercadodetrabalho: "P13_ID_SITUACAO_TRABALHO",
            sine: "P13_NM_SINE",
            ocupacao: "P13_DS_OCUPACAO", 
            remuneracao: "P13_VL_REMUNERACAO",
            beneficioseguro: "P13_ID_BENEFICIO_SEGURO", 
            valordobeneficio: "P13_VL_BENEFICIO_SEGURO", 
            apoioredeprimaria: "P13_FL_APOIO_REDE_PRIMARIA", 
        }  
    },
    valoresMembro: {
        nomecompleto: "Lucas Pereira",
        labeltitular: "Não",
        possuinomesocial: "Sim",
        generolovbtn: "Masculino",
        orientacaosexual: "Homossexual",
        datanascimento: "22-08-2002",
        cpf: "321.654.987-10",
        email: "lucas.pereira@email.com",
        telefone: "(83) 99876-5432",
        nis: "98765432109",
        rg: "7654321",
        nomepai: "Roberto Pereira",
        nomemae: "Cláudia Souza",
        estadocivil: "Solteiro",
        escolaridade: "Ensino Superior Incompleto",
        nacionalidade: "Brasileira",
        naturalidade: "Acre",
        etnia: "Branco",
        demandante: "CRAS Sul",
        numerocartaosus: "123456789012345",
        deficiencia: "Sim",
        comorbidade: "Não",
        medicacao: "Sim",
        orgaoorigem: "CRAS PADRE ZE",
        banco: "CAIXA ECONOMICA FEDERAL",
        agencia: "4321-0",
        conta: "12345-6",
        operacao: "Poupança",
        observacao: "Membro familiar para teste automatizado",

        // Endereço
        cep: "58020-000",
        endereco: "Rua dos Testes",
        numero: "456",
        bairro: "Bancários",
        cidade: "João Pessoa",
        uf: "PB",
        complemento: "Casa B",
        tipo_localidade: "Urbana",
        tipo_construcao: "Alvenaria",
        coabitacao_familiar: "Não",
        iluminacao: "Elétrica",
        domicilio_coberto_por: "P13_FL_DOMICILIO_COBERTO_POR_1",
        abastecimento_de_agua: "Poço",
        esgoto_sanitario: "Rede Pública",
        destino_do_lixo: "Queimado",
        condicao_da_moradia: "Cedida",
        descricao_da_moradia: "Casa pequena, simples",
        tipo_domicilio: "APARTAMENTO",


        // Situação da pessoa
        situacaonomercadodetrabalho: "Estudante",
        sine: "SINE Sul",
        ocupacao: "Estagiário",
        remuneracao: "800",
        beneficioseguro: "BPC",
        valordobeneficio: "0",
        apoioredeprimaria: "Amigos",
    }
}