// This file contains the configuration for the cadastropessoa test suite.
export const cadastropessoa = { 
    baseurl: "https://dev.joaopessoa.pb.gov.br/ords/r/master/social/social0013?session=31207475505279",  

    dadospessoais: {
        selectors: {
            nomecompleto: "P13_NM_PESSOA",
            labeltitular: "P13_FL_TITULAR_LABEL",
            possuinomesocial: "P13_FL_NM_SOCIAL_LABEL",
            generolovbtn: "P13_ID_GENERO",
            orientacaosexual: "P13_NM_ORIENTACAO_SEXUAL",
            datanascimento: "P13_DT_NASCIMENTO_input",
            cpf: "P13_NU_CPF",
            email: "P13_DS_EMAIL",
            telefone: "P13_DS_TELEFONE",
            nis: "P13_NU_NIS",
            rg: "P13_NU_RG",
            nomepai: "P13_NM_PAI",
            nomemae: "P13_NM_MAE",
            estadocivil: "P13_ID_ESTADO_CIVIL", 
            escolaridade: "P13_ID_ESCOLARIDADE",
            nacionalidade: "P13_ID_NACIONALIDADE",
            naturalidade: "P13_ID_NATURALIDADE",
            etnia: "P13_ID_ETNIA",
            demandante: "P13_NM_DEMANDANTE",
            numerocartaosus: "P13_NU_CARTAO_SUS", 
            deficiencia: "P13_FL_DEFICIENCIA_LABEL",
            comorbidade: "P13_FL_COMORBIDADE_LABEL", 
            medicacao: "P13_FL_MEDICACAO_LABEL", 
            orgaoorigem: "P13_ID_ORGAO_ORIGEM",
            banco: "P13_ID_BANCO",
            agencia: "P13_NU_AGENCIA",
            conta: "P13_NU_CONTA",
            operacao: "P13_NU_OPERACAO",
            observacao: "P13_DS_OBSERVACAO_1", 

            // seleção do titular
            //cpftitularresponsavel: "P13_LISTA",

            // endereço (agora em lowercase)
            cep: "P13_NU_CEP",
            endereco: "P13_NM_ENDERECO",
            numero: "P13_NU_ENDERECO",
            bairro: "P13_NM_BAIRRO",
            cidade: "P13_NM_CIDADE",
            uf: "P13_CD_UF",
            complemento: "P13_DS_COMPLEMENTO",
            tipo_localidade: "P13_FL_TIPO_LOCALIDADE",
            tipo_construcao: "P13_FL_TIPO_CONSTRUCAO",
            coabitacao_familiar: "P13_FL_COABITACAO",
            iluminacao: "P13_FL_ILUMINACAO",
            domicilio_coberto_por: "P13_FL_DOMICILIO_COBERTO_POR_LABEL",
            abastecimento_de_agua: "P13_FL_ABASTECIMENTO_AGUA",
            esgoto_sanitario: "P13_FL_ESGOTO",
            destino_do_lixo: "P13_FL_DESTINO_LIXO",
            condicao_da_moradia: "P13_ID_CONDICAO_MORADIA",
            descricao_da_moradia: "P13_DS_IMOVEL",
            tipo_domicilio: "P13_TIPO_DE_DOMICILIO",

            // situação da pessoa 
            situacaonomercadodetrabalho: "P13_ID_SITUACAO_TRABALHO",
            sine: "P13_NM_SINE",
            ocupacao: "P13_DS_OCUPACAO", 
            remuneracao: "P13_VL_REMUNERACAO",
            beneficioseguro: "P13_ID_BENEFICIO_SEGURO", 
            valordobeneficio: "P13_VL_BENEFICIO_SEGURO", 
            apoioredeprimaria: "P13_FL_APOIO_REDE_PRIMARIA", 
        }  
    },
    valores: {
        nomecompleto: "João da Silva",
        labeltitular: "Sim",
        possuinomesocial: "Não",
        generolovbtn: "Masculino",
        orientacaosexual: "Heterossexual",
        datanascimento: "15-01-1996",
        cpf: "123.456.789-00",
        email: "joao.silva@email.com",
        telefone: "(83) 91234-5678",
        nis: "12345678901",
        rg: "1234567",
        nomepai: "Carlos da Silva",
        nomemae: "Maria da Silva",
        estadocivil: "Solteiro",
        escolaridade: "Ensino Médio Completo",
        nacionalidade: "Brasileira",
        naturalidade: "Bahia",
        etnia: "Pardo",
        demandante: "CRAStaubate",
        numerocartaosus: "752644837700006",
        deficiencia: "Não",
        comorbidade: "Não",
        medicacao: "Não",
        orgaoorigem: "CRAS PADRE ZE",
        banco: "BANCO DO BRASIL",
        agencia: "1234-5",
        conta: "98765-4",
        operacao: "Corrente",
        observacao: "Nenhuma observação relevante",

        // Endereço caso seja o titular
        cep: "58015-20",
        endereco: "Ruas das Flores",
        numero: "123",
        bairro: "Centro",
        cidade: "João Pessoa",
        uf: "PB",
        complemento: "Apto 101",
        tipo_localidade: "Rural",
        tipo_construcao: "Taipa",
        coabitacao_familiar: "Sim",
        iluminacao: "Gambiarra",
        domicilio_coberto_por: "P13_FL_DOMICILIO_COBERTO_POR_0",
        abastecimento_de_agua: "Rede Pública",
        esgoto_sanitario: "Fossa",
        destino_do_lixo: "Coletado",
        condicao_da_moradia: "Alugado",
        descricao_da_moradia: "Casa simples, bem arretada",
        tipo_domicilio: "CASA",


        // Situação da pessoa
        situacaonomercadodetrabalho: "Desempregado",
        sine: "SINE Centro",
        ocupacao: "Auxiliar Administrativo",
        remuneracao: "100000",
        beneficioseguro: "BPC",
        valordobeneficio: "1000",
        apoioredeprimaria: "Parentes",
    }
}